[profile.default]
src = "."
out = "out"
libs = ["../node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=../node_modules/@openzeppelin/contracts/"
]
